spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_stackoverflow?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jpa: DEBUG
        sql: DEBUG